# Generated by Django 3.1.7 on 2021-09-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210919_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='articles', to='articles.Keyword'),
        ),
    ]
